redis:
  host: "localhost"
  port: 9379

topic: "temperature_reading"

spring:
  datasource:
    username: sepet
    password: sepet
    url: jdbc:postgresql://localhost:5432/sepet
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
